config/routes.rb
GoalApp::Application.routes.draw do
  resource :session, :only => [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :goals

end

app/models/goal.rb
class Goal < ActiveRecord::Base
   attr_accessible :goal_name, :visibility, :progress, :user_id

   validates :goal_name, presence: true
   validates :visibility, :inclusion => {:in => [true, false]}

   belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :token, :username, :admin
  attr_reader :password

  validates :username, presence: true
  before_validation :reset_session_token

  has_many :goals

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token
    self.token = SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_token(session[:token])
  end

  def signin(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def signout
    session[:token] = nil
  end

  def rcu
    redirect_to new_session_url unless current_user
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :rcu

  def index
    @goals = current_user.goals
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.build(params[:goal])

    if @goal.save
      redirect_to goals_url
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update_attributes(params[:goal])
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to goals_url
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      signin(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = ["Invalid username/password"]
      render :new
    end
  end

  def destroy
    signout
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      signin(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth
    "<input type=\"hidden\"
            name=\"authenticity_token\"
            value=\"#{form_authenticity_token}\">".html_safe
  end

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/goals/edit.html.erb
<h3>Edit Goal</h3>

<form action="<%= goal_url(@goal) %>" method="post">
  <%= auth %>
  <input type="hidden" name="_method" value="put">

  <label>Goal Name
    <input type="text" name="goal[goal_name]" value="<%= @goal.goal_name %>">
  </label>

  <input type="radio" name="goal[visibility]" value="true" id="Private" <%= "checked" if @goal.visibility %>>
  <label>Private</label>

  <input type="radio" name="goal[visibility]" value="false" id="Public" <%= "checked" unless @goal.visibility %>>
  <label>Public</label>

  <input type="radio" name="goal[progress]" value="true" <%= "checked" if @goal.progress %>>
  <label>Completed</label>

  <input type="radio" name="goal[progress]" value="false" <%= "checked" unless @goal.progress %>>
  <label>Not Completed</label>

  <p><input type="submit" value="Update the goal"></p>
</form>

app/views/goals/index.html.erb
<h3>My goals</h3>

<% @goals.each do |goal| %>
  <%= link_to goal.goal_name, goal_url(goal) %> |
  <%= goal.progress ? "Completed" : "Not Completed" %><br>
<% end %>

app/views/goals/new.html.erb
<h3>Create Goal</h3>

<form action="/goals" method="post">
  <%= auth %>

  <label>Goal Name
    <input type="text" name="goal[goal_name]">
  </label>

  <input type="radio" name="goal[visibility]" value="true" id="Private">
  <label>Private</label>

  <input type="radio" name="goal[visibility]" value="false" id="Public">
  <label>Public</label>

  <p><input type="submit" value="Create new goal"></p>
</form>

app/views/goals/show.html.erb
<h3><%= @goal.goal_name %></h3>

<p>
  Type: <%= @goal.visibility %><br>
  Completed?: <%= @goal.progress %>
</p>

<%= link_to "Edit Goal", edit_goal_url %><br>
<%= button_to "Delete Goal", goal_url(@goal), :method => "delete" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>

  <strong>Signed In as: <%= current_user.username %></strong><br>
  <% if current_user.admin %>
    Admin
  <% end %>
  <%= button_to "Sign Out", session_url, method: "delete" %>

<% else %>

  <%= link_to "Sign Up", new_user_url %>
  <%= link_to "Sign In", new_session_url %>

<% end %>

<br><hr><br>

<%= flash[:errors] && flash[:errors].join("<br>").html_safe %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h3>Sign Up</h3>

<form action="/users" method="post">
  <%= auth %>

  <label>username
    <input type="text" name="user[username]">
  </label>

  <label>password
    <input type="password" name="user[password]">
  </label>

  <p><input type="submit" value="Create New User"></p>
</form>